server:
  port: 8090

spring:
  application:
    name: tax-tolls-service

  datasource:
    url: jdbc:postgresql://tax-tolls-postgres:5432/taxtollsdb
    username: uberlite
    password: changeme
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
    locations: classpath:db/migration

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: when-authorized
