#!/usr/bin/env python3
"""Single source of truth for all 14 service Dockerfiles.

The images are identical apart from the module name and port, so they are generated rather than
hand-maintained: editing 14 near-identical files by hand is how `EXPOSE` drifts from `server.port`
and how one service silently keeps an old base image.

    python3 scripts/generate-dockerfiles.py          # rewrite every <module>/Dockerfile
    python3 scripts/generate-dockerfiles.py --check  # CI: fail if a file is stale

The port is read from the module's own application.yml, so the generated file cannot disagree with
the application - `scripts/check-config-consistency.py` then verifies the rest of the chain
(compose, gateway routes).
"""
import glob
import re
import sys

TEMPLATE = '''# syntax=docker/dockerfile:1
# -------------------------------------------------------------------------------------------------
# {module}
#
# GENERATED by scripts/generate-dockerfiles.py - edit the template there, not this file.
#
# The image is self-contained: it needs no other UberLite image to build and no other UberLite
# container to start. That is what makes the service independently deployable - it can be rolled out,
# rolled back or run on its own against a stub, and it degrades (fast 5xx from a Feign call) rather
# than refusing to boot when a peer is missing.
# -------------------------------------------------------------------------------------------------

# --- Stage 1: build ------------------------------------------------------------------------------
# The build context is the repo root because the root pom's reactor needs every module present even
# for a single-module `-pl <module> -am` build. The ~/.m2 cache mount is what keeps that cheap: the
# dependency tree is downloaded once and shared by all 14 image builds, and never lands in a layer.
FROM maven:3.9-eclipse-temurin-25 AS build
WORKDIR /workspace
COPY . .
RUN --mount=type=cache,target=/root/.m2,sharing=locked \\
    mvn -B -pl {module} -am -DskipTests package

# Explode the fat jar into Spring Boot's layers. Dependencies change rarely and application code
# changes every commit, so splitting them means a code-only rebuild pushes/pulls a few hundred KB
# instead of the whole ~60 MB jar.
RUN java -Djarmode=tools -jar {module}/target/{module}-*.jar \\
    extract --layers --launcher --destination /extract

# --- Stage 2: runtime ----------------------------------------------------------------------------
FROM eclipse-temurin:25-jre
LABEL org.opencontainers.image.title="{module}" \\
      org.opencontainers.image.description="UberLite {module}" \\
      org.opencontainers.image.licenses="MIT"

# curl is the HEALTHCHECK probe; the JRE image ships without one. Same layer as the user creation so
# the image carries one apt layer, not two.
RUN apt-get update \\
    && apt-get install -y --no-install-recommends curl \\
    && rm -rf /var/lib/apt/lists/* \\
    && useradd --system --uid 10001 --user-group --no-create-home uberlite

WORKDIR /app
# Ordered least- to most-frequently-changed, so a code change only invalidates the last COPY.
COPY --from=build --chown=10001:10001 /extract/dependencies/ ./
COPY --from=build --chown=10001:10001 /extract/spring-boot-loader/ ./
COPY --from=build --chown=10001:10001 /extract/snapshot-dependencies/ ./
COPY --from=build --chown=10001:10001 /extract/application/ ./

# Numeric so the check still holds if /etc/passwd is ever rewritten, and so Kubernetes can enforce
# runAsNonRoot without resolving a name.
USER 10001:10001
EXPOSE {port}

# Liveness, NOT the composite /actuator/health. "Is this JVM serving?" is the only question a
# container runtime can act on, because the only remedy it has is a restart - and restarting this
# service will never fix a sick Postgres or a late Eureka. Probing the composite instead made a
# dependency blip look like a fault here, which is exactly what makes `docker compose up` report the
# wrong service as broken. Readiness (which does include this service's own datastore) is the
# separate /actuator/health/readiness group defined in common's uberlite-defaults.yml.
HEALTHCHECK --interval=10s --timeout=3s --start-period=60s --retries=6 \\
    CMD curl -fsS http://localhost:{port}/actuator/health/liveness || exit 1

# JDK_JAVA_OPTIONS is read by the `java` launcher itself, so no `sh -c` wrapper is needed: the JVM is
# PID 1 and receives SIGTERM directly, which is what makes Boot's graceful shutdown actually run.
# MaxRAMPercentage because a container gets a slice of the host's RAM, not all of it; ExitOnOOM so a
# heap-exhausted JVM dies and is restarted instead of thrashing at 100% CPU forever.
ENV JDK_JAVA_OPTIONS="-XX:MaxRAMPercentage=75 -XX:+ExitOnOutOfMemoryError"
ENTRYPOINT ["java", "org.springframework.boot.loader.launch.JarLauncher"]
'''


def modules():
    """Every module that is a deployable service, i.e. has a server.port."""
    found = {}
    for path in sorted(glob.glob("*/src/main/resources/application.yml")):
        module = path.split("/")[0]
        default_doc = open(path).read().split("\n---")[0]
        port = re.search(r"^\s*port:\s*(\d+)", default_doc, re.M)
        if port:
            found[module] = port.group(1)
    return found


def main():
    check = "--check" in sys.argv
    stale = []
    for module, port in modules().items():
        rendered = TEMPLATE.format(module=module, port=port)
        path = f"{module}/Dockerfile"
        try:
            current = open(path).read()
        except FileNotFoundError:
            current = None
        if current == rendered:
            continue
        if check:
            stale.append(path)
        else:
            open(path, "w").write(rendered)
            print(f"wrote {path}")

    if stale:
        print("Stale Dockerfiles (run scripts/generate-dockerfiles.py):", file=sys.stderr)
        for path in stale:
            print(f"  - {path}", file=sys.stderr)
        return 1
    print("All Dockerfiles up to date." if check else "Done.")
    return 0


if __name__ == "__main__":
    sys.exit(main())

